DjangoProject/base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teplo.urls')),
]

handler404 = page_not_found

# Admin panel styles
admin.site.site_header = 'Панель администратора'
admin.site.index_title = 'ESK-Teplo'

base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('teplo.urls')),
    path('captcha/', include('captcha.urls')),
]

handler404 = page_not_found

# Admin panel styles
admin.site.site_header = 'Панель администратора'
admin.site.index_title = 'ESK-Teplo'

teplo/urls.py
from django.urls import path
from . import views


# Routing:
app_name = 'teplo'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('service/', views.service, name='service'),
    path('price/', views.price, name='price'),
]

DjangoProject/teplo/models.py
from django.core.validators import MinValueValidator, MaxValueValidator, MinLengthValidator, MaxLengthValidator, \
    RegexValidator
from django.db import models
from django.utils import timezone


class FromForm(models.Model):
    """Data from form"""
    name = models.CharField(validators=[
        MinLengthValidator(2, message="Минимальное количество символов 2"),
        MaxLengthValidator(30, message="Максимальное количество символов 30"),
        RegexValidator(regex=r'[абвгдеёжзийклмнопрстуфхцчшщъыьэюя .]',
                       message='Только русские буквы, пробелы и точки')
    ])

    phone = models.CharField(validators=[
        MinLengthValidator(10, message="Минимальное количество символов 10"),
        MaxLengthValidator(12, message="Максимальное количество символов 12"),
        RegexValidator(regex=r'^(\+)?[0-9]{10,11}', message='Только цифры и знак +')
    ])

    order = models.CharField(validators=[
        MinLengthValidator(5, message="Минимальное количество символов 5"),
        MaxLengthValidator(1000, message="Максимальное количество символов 1000")
    ])

    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Заявки из формы обратной связи'
        verbose_name_plural = 'Заявки из формы обратной связи'


class Price(models.Model):
    """Data from admin"""
    service = models.CharField(validators=[
        MinLengthValidator(1, message="Минимальное количество символов 1"),
        MaxLengthValidator(100, message="Максимальное количество символов 100")
    ], unique=True)

    cost = models.IntegerField(validators=[
        MinValueValidator(1, message="Минимальное значение 1"),
        MaxValueValidator(99999, message="Максимальное значение 99999")
    ])
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.service

    class Meta:
        verbose_name = 'Прайс лист'
        verbose_name_plural = 'Прайс лист'
        ordering = ['-cost']

DjangoProject/teplo/forms.py
from django import forms
from teplo.models import FromForm


class ToMailForm(forms.ModelForm):
    class Meta:
        model = FromForm
        fields = ['name', 'phone', 'order']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-input',
                'placeholder': 'Ваше имя',
                'minlength': 2,
                'maxlength': 30
            }),
            'phone': forms.TextInput(attrs={
                'class': 'form-input',
                'placeholder': 'Ваш телефон',
                'minlength': 10,
                'maxlength': 12
            }),
            'order': forms.Textarea(attrs={
                'class': 'form-area',
                'rows': 5,
                'placeholder': 'Напишите заявку сюда..',
                'minlength': 5,
                'maxlength': 1000
            })
        }
        labels = {
            'name': False,
            'phone': False,
            'order': False
        }

DjangoProject/teplo/views.py
from django.shortcuts import render, redirect
from teplo.forms import ToMailForm
from .models import Price
from django.contrib import messages
from django.core.mail import send_mail


def index(request):
    """Main page"""
    if request.method == 'POST':
        form = ToMailForm(request.POST)
        if form.is_valid():
            form.save()
            send_mail(
                "Заявка",
                str(form.cleaned_data),
                "shadow-of-toilet@yandex.ru",
                ["shadow-of-toilet@yandex.ru"],
                fail_silently=False,
            )
            messages.success(request, 'Заявка успешно отправлена! Мы свяжемся в Вами в ближайшее время.')
            return redirect('/')
    else:
        form = ToMailForm()

    form_data = {
        'title': "главная",
        'form': form
    }

    return render(request, 'teplo/index.html', context=form_data)


def about(request):
    """About page"""
    return render(request, 'teplo/about.html', {'title': 'о нас'})


def service(request):
    """Services page"""
    return render(request, 'teplo/service.html', {'title': 'услуги'})


def price(request):
    """Price page"""
    price_data = {
        'title': 'цены',
        'db_price': Price.objects.all(),
    }
    return render(request, 'teplo/price.html', context=price_data)

DjangoProject/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Энергосервисная Компания Тепло. Обслуживание ИТП, АУУ, КНС, НС, УУТЭ по г. Москве."/>
    <link rel="shortcut icon" href="{% static 'teplo/img/favicon.png' %}" type="image/x-icon"/>
    <link type="text/css" href="{% static 'teplo/css/style.css' %}" rel="stylesheet" />
    <title>{{ title|capfirst }}</title>
</head>
<body class="container">
    <header class="header">
        <nav class="nav">
            {% with request.resolver_match.url_name as url_name %}
            <div class="nav-logo"></div>
            <div class="nav-menu">
                <div class="nav-item">
                    <a class="page {% if url_name == 'home' %} active {% endif %}" href="{% url 'teplo:home' %}">
                        ГЛАВНАЯ
                    </a>
                </div>

                <div class="nav-item">
                    <a class="page {% if url_name == 'about' %} active {% endif %}" href="{% url 'teplo:about' %}">
                        О НАС
                    </a>
                </div>

                <div class="nav-item">
                    <a class="page {% if url_name == 'service' %} active {% endif %}" href="{% url 'teplo:service' %}">
                        УСЛУГИ
                    </a>
                </div>

                <div class="nav-item">
                    <a class="page {% if url_name == 'price' %} active {% endif %}" href="{% url 'teplo:price' %}">
                        ЦЕНЫ
                    </a>
                </div>
            </div>
            {% endwith %}
        </nav>
    </header>

    <main class="main">
        {% block main %}
        {% endblock main %}
    </main>

    <footer class="footer">
        <div class="footer-links">
            <div class="footer-mail"><a class="mail" href="mailto:info@esk-teplo.ru" target="_blank">
                <img src="{% static 'teplo/img/mail.svg' %}" alt="mail">&nbsp;info@esk-teplo.ru</a>
            </div>

            <div class="footer-tel"><a class="tel" href="tel:+79654128898" target="_blank">
                <img src="{% static 'teplo/img/phone.svg' %}" alt="tel">&nbsp;+7 (965) 412-88-98</a>
            </div>

            <div class="footer-wapp"><a class="wapp" href="https://wa.me/+79654128898" target="_blank" rel="noreferrer">
                <img src="{% static 'teplo/img/whatsapp.svg' %}" alt="wapp" height="15">&nbsp;WhatsApp</a>
            </div>
        </div>

        <p class="copyright">&copy; 2024, ESK-Teplo</p>
    </footer>

    {% block script %} {% endblock script %}
</body>
</html>